<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ItHelpdesk</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\LanguageController.cs" />
    <Compile Remove="Controllers\LanguageTextController.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ItHelpdesk.Application.Contracts\ItHelpdesk.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" Version="10.7.0-rc.3" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" Version="10.7.0-rc.3" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" Version="10.7.0-rc.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Identity.HttpApi" Version="10.7.0-rc.3" />
    <PackageReference Include="Volo.Abp.Account.HttpApi" Version="10.7.0-rc.3" />
    <PackageReference Include="Volo.Abp.TenantManagement.HttpApi" Version="10.7.0-rc.3" />
  </ItemGroup>

</Project>
